# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('supers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='login_app.User'),
        ),
    ]
