# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers_app', '0002_hero_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='likes',
            new_name='liked',
        ),
    ]
